name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for TypeScript errors
        run: npm run build
        continue-on-error: false

      - name: Check server build
        run: cd server && npm run build
        continue-on-error: false

      # Add more checks as needed:
      # - name: Run tests
      #   run: npm test

      # - name: Run linting
      #   run: npm run lint
